# Generated by Django 4.2.2 on 2023-06-17 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='profiles/')),
                ('birth_date', models.DateField(verbose_name='Birthday date')),
                ('bio', models.TextField()),
                ('country', models.CharField(max_length=100, null=True, verbose_name='Country')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('interests', models.TextField(max_length=400, verbose_name='Interests')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('time_created', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='notes/')),
                ('time_updated', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
