name: Python linters

on:
  push:
    branches: [ "main" , "development"]
  pull_request:
    branches: [ "main" , "development"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: flake8 Lint
      uses: py-actions/flake8@v2
      with:
          ignore: "F401"
          max-line-length: "120"
          path: "."
    - name: mypy
      uses: konciergeMD/github-action-mypy@main
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MYPY_OPTS: "--config=./mypy.ini"  # additional mypy options
          #MYPY_CODE_DIR: "."  # what directory to check, defaults to "."
          #PRECOMMAND_MESSAGE: You have style errors. See them below.
          
